### ISSUE TITLE
Hapi 8 and updated docs

### ISSUE THREAD

**Issue by landau** [blinkmobile/hapi-oauth2orize#5]
Any word on testing with Hapi 8+?
Also, updated docs?

My team is looking to implement oauth for our API so we may be able to help contrib to this module.

Cheers.

**Comment by devinivy** [comment]
We'd love a PR!  I don't expect it'll take many changes.  I will need to update this to hapi 8 soon regardless (since my team would like to upgrade our oauth service)!  Ideally the update should support hapi 7 and 8.

As an aside, if you're building an API, maybe take a peek at [dogwater](https://github.com/devinivy/dogwater) (integration with Waterline ORM) and [bedwetter](https://github.com/devinivy/bedwetter) (model-aware API builder based on Github's API style).

**Comment by landau** [comment]
Thanks for the suggestions!

**Comment by marcosbergamo** [comment]
This project still continue?

**Comment by devinivy** [comment]
@marcosbergamo indeed!

**Comment by marcosbergamo** [comment]
Tks =D

**Comment by cwurtz** [comment]
Is there any eta on support for Hapi 8.x?  Thanks

**Comment by devinivy** [comment]
There's no ETA at the moment, but I would certainly take a PR.  I've made a new placeholder issue for this at #6 and assigned it to the 2.0.0 milestone.

**Comment by devinivy** [comment]
Hey all, just updated this for hapi8 and hapi9.  I'd like to improve docs and do some testing before publishing 2.0.0, but please feel free to give it a try.  Closed in #6, PR #8.
